### ISSUE TITLE
Hopscotch modification shortcut is broken as of iPadOS14...

### ISSUE THREAD

**Issue by Syringegoogleplex** [Awesome-E/awesome-e.github.io#1]
...Although I’m not sure about iOS14.
![Screenshot of bug](https://user-images.githubusercontent.com/27730166/87944538-6e711a80-ca97-11ea-8034-51dcf905ec4d.png)

It may be worth updating the shortcut to fix this, so that the problem doesn’t affect the community at a larger scale in the future. iPadOS13 came out of beta after approximately three months, so that’s probably how long you have to fix it.

In the hopscotch community you may know me @DoNotCopyMe or Musicguy32. I’m sorry for saying that you were being rude.

**Comment by Awesome-E** [comment]
Apologies for not making this clear everywhere – the shortcut only supports iOS versions 11-13, as listed in the help guide. I don't plan to update it any more, and I highly recommend learning the [Web Builder](https://awesome-e.github.io/hs-tools/hs-builder/) instead, as it provides all functionality within the shortcut already and gives a much more control of edits as opposed to a one-runtime script.

As for fixing the issue you have, I believe that you also are not on the latest version of the shortcut. Get the latest version [here](https://www.icloud.com/shortcuts/360b1617bb77475496f69883550e76ad). Let me know if that fixes the issue.

However, since all iOS 13 devices can update to iOS 14, I will definitely keep this in mind if I decide to update the shortcut.

**Comment by Syringegoogleplex** [comment]
I consider myself quite the shortcut developer. I have looked through some of the code, and I have no idea how this happened...
Apple needs to get something right, and it has to be something other than their sound recognition...
![Another Shortcut Bug...](https://user-images.githubusercontent.com/27730166/87973282-29151300-cac0-11ea-844f-08eace04a1ca.png)
(That’s the latest version, the first issue was the version linked on your GitHub io page)

**Comment by Syringegoogleplex** [comment]
Also, “shortcut No4b1lity”...

**Comment by Awesome-E** [comment]
The shortcut is already kind of broken as is on iOS 13, and I don't have the time or plans to spend on fixing issues with iOS 14 when I can be doing things like the Project Builder on the web. I know some people have had success with redownloading the latest version of the shortcut [here](https://www.icloud.com/shortcuts/360b1617bb77475496f69883550e76ad) (you can also ask questions there), but I don't think I can help much with this issue.
